<?php

namespace Tests\Feature;

use App\Category;
use App\User;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Support\Facades\Auth;
use Tests\TestCase;

class CategoryTest extends TestCase
{

    use RefreshDatabase;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $user = factory(User::class)->create();
        Auth::loginUsingId($user->id);
    }

    /** @test */
    public function see_page_to_create_category()
    {
        $this->get(route('category.create'))
            ->assertStatus(200);
    }

    /** @test */
    public function list_categories()
    {
        $this->withoutExceptionHandling();

        $categories = factory(Category::class, 5)->create();

        $this->get(route('category.index'))
            ->assertStatus(200)
            ->assertSee($categories[1]->name);
    }

    /** @test */
    public function create_a_new_category()
    {
        $this->post(route("category.store"), [
            'name' => 'Category Name'
        ])->assertStatus(302);

        $this->assertDatabaseHas("categories", ['name' => 'Category Name']);
    }

    /** @test */
    public function update_a_category()
    {
        $category = factory(Category::class)->create();

        $this->assertDatabaseHas("categories", ['name' => $category->name]);

        $this->put(route("category.update"), [
            'id' => $category->id,
            'name' => 'New Name'
        ])->assertStatus(302);

        $this->assertEquals($category->fresh()->name, 'New Name');
    }

}
